import Config from "react-native-config";


//'https://dev-gateway.invia.com.au/api/mWallet/'       
//'http://103.225.161.88:8094/api/mWallet/'
//'http://103.225.161.88:8091/api/mWallet/'

export const BaseUrl = Config.baseUrl   //'https://dev-gateway.invia.com.au/api/mWallet/' //
export const ChkNameEmail = 'ChkNameEMail'
export const EmailVerified = 'EmailVerified'
export const ChkMobile = 'ChkMobile'
export const MobileVerified = 'MobileVerified'
export const VerifyOTP = 'VerifyOTP'
export const CreateRegPIN = 'CreateRegPIN'
export const GetTermsNCondition = 'GetTermsNCondition'
export const GetPrivacyPolicy = 'GetPrivacyPolicy'
export const AcceptTNC = 'AcceptTNC'
export const UploadImage = 'UploadImage'
export const GetBrandList = 'GetBrandList'
export const AddBrandToUser = 'AddBrandToUser'
export const Login = 'Login'
export const Login2 = 'Login2'
export const ForgottenPin = 'ForgottenPin'
export const GetCategoriesWithOffers = 'GetCategoriesWithOffers'
export const GetCategoriesWithOffers2 = 'GetCategoriesWithOffers2'
export const GetAllCategories = 'GetAllCategories'
export const GetAllAggMerchants = "GetAllAggMerchants"
export const GetAggMerchantsByCat = "GetAggMerchantsByCat"
export const SaveOffers = 'SaveOffers'
export const ShopClickAPI = 'ClickHistory'
export const GetSavedOffers = 'GetCategoriesWithOffersByUser'
export const GetSavedOffers2 = 'GetCategoriesWithOffersByUser2'
export const GetRewardCategories = 'GetRewardCategories'
export const GetRewardDetails = 'GetRewardDetails'
export const MatchContact = 'MatchContact'
export const GetBalance = 'GetBalance'
export const RequestGiftcard = 'RequestGiftcard'
export const GetUserProfile = 'GetUserProfile'
export const GetFavBrands = 'GetFavBrands'
export const GetGiftsRewards = 'GetGiftsRewards'
export const EditProfile = 'EditProfile'
export const GetPOSMerProds = 'GetPOSMerProds'
export const POSRequest = 'POSRequest'
export const GetBankDetails = 'GetBankDetails'
export const SendMoneyToUser = 'SendMoneyToUser'
export const RequestMoney = 'RequestMoney'
export const GetRequestedTrans = 'GetRequestedTrans'
export const SendRequestMoney = 'SendRequestMoney'
export const MakePayment = 'MakePayment'
export const GetPointsHistory = 'GetPointsHistory'
export const GetMoneyHistory = 'GetMoneyHistory'
export const TransferPoints = 'TransferPoints'
export const UpdateFCMToken = 'UpdateFCMToken'
export const NotificationSeen = 'NotificationSeen'
export const NotificationDelete = 'NotificationDelete'
export const ForceUpdate = 'ForceUpdate'
export const GetNotifications = 'GetNotifications'
export const MaintenanceStatus = 'MaintenanceStatus'
export const RequestWoolworth = 'RequestWoolworth'
export const GetDevices = 'GetDevices'
export const GetAccessories = 'GetAccessories'
export const CreateCommunity = 'CreateCommunity'
export const GetCommunities = 'GetCommunitiesByUser'
export const GetAllCommunities = 'GetAllCommunities'
export const GetAlertStatus = 'GetAlertStatus'
export const SaveAlert = 'SaveAlert'
export const RequestTimeConsent = 'RequestTimeConsent'
export const PostCommunityComments = 'PostCommunityComments'
export const JoinCommunity = 'JoinCommunity'
export const EditCommunity = 'EditCommunity'
export const SwitchTimeConsent = 'SwitchTimeConsent'
export const GetTimeConsentStatus = 'GetTimeConsentStatus'
export const GetChat = 'GetChat'
export const SendChatMsg = 'SendChatMsg'
export const GetChatID = 'GetChatID'
export const GetMsgThread = 'GetMsgThread'
export const SetTarget = 'SetTarget'
export const AddSecondaryUsers = 'AddSecondaryUsers'
export const RemoveSecondaryUsers = 'RemoveSecondaryUsers'
export const IsUserExist = 'IsUserExist'
export const CheckUserStatus = 'CheckUserStatus'
export const GetFeedbackTitles = 'GetFeedbackTitles'
export const GetCallDetails = 'GetCallDetails'
export const RequestFeedback = 'RequestFeedback'
export const GetSecondaryUsers = 'GetSecondaryUsers'
export const GetHeroTiles = 'GetHeroTiles'
export const GetDailyOffers = 'GetDailyOffers'
export const GetPopularOffers = 'GetPopularOffers'
export const GetClickHistory = 'GetClickHistory'
export const GetClickHistorySearch = 'GetClickHistorySearch'
export const SubmitRewardClaim = 'SubmitRewardClaim'
export const GetChallenges = 'GetChallenges'
export const TransferMoney = 'TransferMoney'
export const ChangePin = 'ChangePin'
export const VerifyReferralCode = 'VerifyReferralCode'
export const GenerateCode = 'GenerateCode'
export const GetReferralCode = 'GetReferralCode'
export const AddUpdateBankDetails = 'AddUpdateBankDetails'
export const DeleteBankDetails = 'DeleteBankDetails'
export const EditEmail = 'EditEmail'
export const EditMobile = 'EditMobile'
export const RequestDigiCard = 'RequestDigiCard'
export const DeleteUser = 'DeleteUser'
export const access_token = 'access_token'
export const CreateToken = 'CreateToken'















