//SIGN_UP_2
export const SEND_NAME_AND_EMAIL_REQUEST = 'SEND_NAME_AND_EMAIL_REQUEST';
export const SEND_NAME_AND_EMAIL_RESPONSE =  'SEND_NAME_AND_EMAIL_RESPONSE';
export const SEND_NAME_AND_EMAIL_RESET =  'SEND_NAME_AND_EMAIL_RESET';

//Email verified 
export const EMAIL_VERIFIED_REQUEST = 'EMAIL_VERIFIED_REQUEST';
export const EMAIL_VERIFIED_RESPONSE =  'EMAIL_VERIFIED_RESPONSE';
export const EMAIL_VERIFIED_RESET =  'EMAIL_VERIFIED_RESET';

//Send Mobile Number 
export const SEND_MOBILE_NUMBER_REQUEST = 'SEND_MOBILE_NUMBER_REQUEST';
export const SEND_MOBILE_NUMBER_RESPONSE =  'SEND_MOBILE_NUMBER_RESPONSE';
export const SEND_MOBILE_NUMBER_RESET =  'SEND_MOBILE_NUMBER_RESET';

//OTP verified 
export const OTP_VERIFIED_REQUEST = 'OTP_VERIFIED_REQUEST';
export const OTP_VERIFIED_RESPONSE =  'OTP_VERIFIED_RESPONSE';
export const OTP_VERIFIED_RESET =  'OTP_VERIFIED_RESET';

//Verify Email and Mobile 
export const VERIFY_EMAIL_AND_MOBILE_REQUEST = 'VERIFY_EMAIL_AND_MOBILE_REQUEST';
export const VERIFY_EMAIL_AND_MOBILE_RESPONSE =  'VERIFY_EMAIL_AND_MOBILE_RESPONSE';
export const VERIFY_EMAIL_AND_MOBILE_RESET =  'VERIFY_EMAIL_AND_MOBILE_RESET';

//Send 6 digit pin 
export const SEND_PIN_REQUEST = 'SEND_PIN_REQUEST';
export const SEND_PIN_RESPONSE =  'SEND_PIN_RESPONSE';
export const SEND_PIN_RESET =  'SEND_PIN_RESET';

//Get T&C 
export const GET_TC_REQUEST = 'GET_TC_REQUEST';
export const GET_TC_RESPONSE =  'GET_TC_RESPONSE';
export const GET_TC_RESET =  'GET_TC_RESET';

//Get Privacy Policy
export const GET_PP_REQUEST = 'GET_PP_REQUEST';
export const GET_PP_RESPONSE =  'GET_PP_RESPONSE';
export const GET_PP_RESET =  'GET_PP_RESET';

//Accept T&C 
export const ACCEPT_TC_REQUEST = 'ACCEPT_TC_REQUEST';
export const ACCEPT_TC_RESPONSE =  'ACCEPT_TC_RESPONSE';
export const ACCEPT_TC_RESET =  'ACCEPT_TC_RESET';

//Upload image 
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_RESPONSE =  'UPLOAD_IMAGE_RESPONSE';
export const UPLOAD_IMAGE_RESET =  'UPLOAD_IMAGE_RESET';

//Get top 10 brands
export const GET_TOP_BRANDS_REQUEST = 'GET_TOP_BRANDS_REQUEST';
export const GET_TOP_BRANDS_RESPONSE =  'GET_TOP_BRANDS_RESPONSE';
export const GET_TOP_BRANDS_RESET =  'GET_TOP_BRANDS_RESET';

//Save favourites 
export const SAVE_FAVOURITES_REQUEST = 'SAVE_FAVOURITES_REQUEST';
export const SAVE_FAVOURITES_RESPONSE =  'SAVE_FAVOURITES_RESPONSE';
export const SAVE_FAVOURITES_RESET =  'SAVE_FAVOURITES_RESET';

